### ISSUE TITLE
archive this repo

### ISSUE THREAD

**Issue by frosty-geek** [SovereignCloudStack/rally-foo#7]
Hi,

since we've moved on from our early rally tests in favor of cloudmon, I suggest that we're archiving this repo.

comments?

Ralf

**Comment by itrich** [comment]
If no one objects, I will sunset this repository next week.

/remind-me next week to merge SovereignCloudStack/github-manager#63 and close this issue

**Comment by fkr** [comment]
👍 on the archiving
